name: azamfc_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^13.2.0
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  flutter_html: ^3.0.0-beta.2
  video_player: ^2.8.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
